name: The Crystal Programming Language
description: A compiled language with Ruby like syntax and type inference
url: http://crystal-lang.org
logo: /images/crystal-h.png
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      image: /images/icon.png
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      image: /images/icon.png
      layout: post
twitter:
  username: CrystalLanguage

highlighter: rouge
markdown: kramdown
exclude: ["*.haml", "Gemfile", "Gemfile.lock", "Rakefile", "travis-build.sh", "scripts/*.cr", "vendor"]
gems:
  - jekyll-seo-tag

# Default key only works for https://crystal-lang.org/ - for dev get yours at https://console.developers.google.com/apis/credentials
google_calendar_api_key: 'AIzaSyCv-2Npqm0mwmwVCKX8xDPhwtP_8HwCWCE'
google_calendar_id: 'manas.com.ar_jb15sr9uhrtjtge4jq94rb51kk@group.calendar.google.com'
