logo: /images/crystal-h.png
name: "Crystal \\| SF2017"
description: "A 2 day hands-on training dictated by the language's core team"
url: https://codecamp.crystal-lang.org
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      image: /images/icon.png
      layout: default
twitter:
  username: CrystalLanguage

highlighter: rouge
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "travis-build.sh", "scripts/*.cr", "vendor"]
gems:
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-timeago
