version: '2'

services:
  web:
    image: ruby:2.2
    working_dir: /src
    command: /bin/bash -c "bundle install --jobs=3 && jekyll serve --host=0.0.0.0 --incremental"
    ports:
      - "4000:4000"
    volumes:
      - .:/src
      - bundle:/usr/local/bundle

volumes:
  bundle:
